---
- name: Установка и настройка OpenLDAP
  hosts: all
  become: yes
  tasks:
    - name: Установка пакетов OpenLDAP
      apt:
        name:
          - slapd
          - ldap-utils
        state: present

    - name: Установка пароля администратора LDAP
      debconf:
        name: slapd
        question: slapd/password1
        value: <admin_password>
        vtype: password

    - name: Установка домена LDAP
      debconf:
        name: slapd
        question: slapd/domain
        value: <domain_name>
        vtype: string

    - name: Установка организации LDAP
      debconf:
        name: slapd
        question: slapd/organization
        value: <organization_name>
        vtype: string

    - name: Перезапуск службы slapd
      service:
        name: slapd
        state: restarted

    - name: Добавление пользователей в LDAP
      ldap_entry:
        dn: "cn=user1,dc=<domain_name>,dc=<tld>"
        objectClass: posixAccount
        cn: user1
        uid: user1
        uidNumber: 10001
        gidNumber: 10001
        homeDirectory: /home/user1
        loginShell: /bin/bash
        userPassword: <user1_password>

    - name: Добавление групп в LDAP
      ldap_entry:
        dn: "cn=group1,dc=<domain_name>,dc=<tld>"
        objectClass: posixGroup
        cn: group1
        gidNumber: 10001
        memberUid:
          - user1

    - name: Добавление второго пользователя в LDAP
      ldap_entry:
        dn: "cn=user2,dc=<domain_name>,dc=<tld>"
        objectClass: posixAccount
        cn: user2
        uid: user2
        uidNumber: 10002
        gidNumber: 10001
        homeDirectory: /home/user2
        loginShell: /bin/bash
        userPassword: <user2_password>

    - name: Добавление второй группы в LDAP
      ldap_entry:
        dn: "cn=group2,dc=<domain_name>,dc=<tld>"
        objectClass: posixGroup
        cn: group2
        gidNumber: 10002
        memberUid:
          - user2
